import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module'
import esbuildSvelte from "esbuild-svelte";
import sveltePreprocess from "svelte-preprocess";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin

String.fromCharCode/atob/btoa usage originates from bundled dependencies:
- isomorphic-git (Git protocol binary operations)
- buffer polyfill (base64 encoding)
- unified/remark (Markdown parser)
*/
`;

const prod = (process.argv[2] === 'production');

esbuild.build({
	banner: {
		js: banner,
	},
	entryPoints: ['main.ts'],
	bundle: true,
	external: ['obsidian', 'electron', ...builtinModules.filter(m => m !== 'buffer')],
	format: 'cjs',
	target: 'es2024',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	minify: prod ? true : false,
	treeShaking: true,
	drop: prod ? ['console'] : [],
	outfile: 'main.js',
	inject: ['./esbuild-buffer-shim.js'],
	platform: 'browser',
	define: {
		'global': 'globalThis',
	},
	plugins: [
		esbuildSvelte({
			compilerOptions: { css: 'injected', dev: !prod },
			preprocess: sveltePreprocess({
				typescript: {
					compilerOptions: {
						module: "esnext",
						verbatimModuleSyntax: true,
					},
				},
			}),
		}),
	],
}).catch(() => process.exit(1));
